openapi: 3.0.0
info:
  title: Ooh Interview API
  description: Provides access to inventory.
  version: '0.1'

servers:
  - url: /api/v1

paths:
  /faces:
    get:
      summary: Returns a list of faces
      description: ''
      tags:
        - Inventory
      responses:
        '200':
          description: A JSON object containing a list of faces
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: '#/components/schemas/FaceList'
                required:
                  - items

  /avails:
    post:
      summary: Returns availability of a list of faces
      description: ''
      tags:
        - Availability
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvailsInput'
      responses:
        '200':
          description: A JSON object containing a list of availabilities
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: '#/components/schemas/AvailsList'
                required:
                  - items
        '400':
          $ref: '#/components/responses/BadRequest'

  /campaigns:
    get:
      summary: Returns a list of campaigns
      description: ''
      tags:
        - Campaign
      responses:
        '200':
          description: A JSON object containing a list of campaigns
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: '#/components/schemas/CampaignList'
                required:
                  - items

  /campaign/{id}/bookings:
    get:
      summary: Returns a list of bookings for a specific campaign
      description: ''
      tags:
        - Campaign
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A JSON object containing a list of bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: '#/components/schemas/BookingList'
                required:
                  - items

components:
  schemas:
    Error:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string

    Face:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
      required:
        - id
        - name

    Avails:
      type: object
      properties:
        faceId:
          type: string
          readOnly: true
        isAvailable:
          type: boolean
      required:
        - faceId
        - isAvailable

    Campaign:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        startDate:
          type: string
        endDate:
          type: string
      required:
        - id
        - name
        - startDate
        - endDate

    Booking:
      type: object
      properties:
        faceId:
          type: string
          readOnly: true
      required:
        - faceId

    FaceList:
      type: array
      items:
        $ref: '#/components/schemas/Face'

    AvailsInput:
      type: object
      properties:
        startDate:
          type: string
        endDate:
          type: string
        faceIds:
          description: A comma separated list of face ids to get availability for.
          type: string
      required:
        - startDate
        - endDate
        - faceIds

    AvailsList:
      type: array
      items:
        $ref: '#/components/schemas/Avails'

    CampaignList:
      type: array
      items:
        $ref: '#/components/schemas/Campaign'

    BookingList:
      type: array
      items:
        $ref: '#/components/schemas/Booking'

    JsonApiErrorObject:
      type: object
      properties:
        type:
          type: string
          description: Identifies the error type. Does not change between occurrences of the error.
        title:
          type: string
          description: Human-readable summary of the error.
        detail:
          type: string
          description: Human-readable details specific to this occurrence of the error.

    JsonApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/JsonApiErrorObject'
      required:
        - errors
      
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JsonApiError'

tags:
  - name: Inventory
    description: Fetch inventory information